// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcOb04rYbjJkNiz4fIspE6e8BDEaW9ZPY',
    appId: '1:810962874550:web:93c87d3a4c8af5e4baf617',
    messagingSenderId: '810962874550',
    projectId: 'decidematepro',
    authDomain: 'decidematepro.firebaseapp.com',
    storageBucket: 'decidematepro.firebasestorage.app',
    measurementId: 'G-MSXJ3PSX8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS2Uyi7juwGdVBLnMj6hHtSJvB2RJ3XM0',
    appId: '1:810962874550:android:639eab328a424c11baf617',
    messagingSenderId: '810962874550',
    projectId: 'decidematepro',
    storageBucket: 'decidematepro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASdM7QxjSFMeAEoqWE5R9wjBo0NZmaJAk',
    appId: '1:810962874550:ios:70d7ee47acd80a1bbaf617',
    messagingSenderId: '810962874550',
    projectId: 'decidematepro',
    storageBucket: 'decidematepro.firebasestorage.app',
    iosBundleId: 'com.amazingappsdev.decidematepro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASdM7QxjSFMeAEoqWE5R9wjBo0NZmaJAk',
    appId: '1:810962874550:ios:ba749a8396c555a6baf617',
    messagingSenderId: '810962874550',
    projectId: 'decidematepro',
    storageBucket: 'decidematepro.firebasestorage.app',
    iosBundleId: 'com.example.decidematePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcOb04rYbjJkNiz4fIspE6e8BDEaW9ZPY',
    appId: '1:810962874550:web:b51de4c07d743335baf617',
    messagingSenderId: '810962874550',
    projectId: 'decidematepro',
    authDomain: 'decidematepro.firebaseapp.com',
    storageBucket: 'decidematepro.firebasestorage.app',
    measurementId: 'G-67PES2YG6P',
  );
}
